-- Analytics global do Catalogo de Midias
-- A tabela nao fica acessivel diretamente para anon/authenticated.
-- O frontend usa somente as funcoes RPC explicitamente liberadas no final.

create table if not exists public.catalogo_search_events (
  id bigint generated by default as identity primary key,
  termo text not null check (char_length(termo) between 2 and 120),
  termo_normalizado text not null check (char_length(termo_normalizado) between 2 and 120),
  programa text null check (programa is null or char_length(programa) <= 120),
  resultados integer not null default 0 check (resultados between 0 and 1000000),
  dedupe_token text not null unique check (char_length(dedupe_token) between 16 and 128),
  created_at timestamptz not null default now()
);

create index if not exists idx_catalogo_search_events_created_at
  on public.catalogo_search_events (created_at desc);
create index if not exists idx_catalogo_search_events_termo_data
  on public.catalogo_search_events (termo_normalizado, created_at desc);
create index if not exists idx_catalogo_search_events_programa_data
  on public.catalogo_search_events (programa, created_at desc)
  where programa is not null;
create index if not exists idx_catalogo_search_events_sem_resultado
  on public.catalogo_search_events (created_at desc, termo_normalizado)
  where resultados = 0;

alter table public.catalogo_search_events enable row level security;
revoke all on table public.catalogo_search_events from anon, authenticated;
revoke all on sequence public.catalogo_search_events_id_seq from anon, authenticated;

create or replace function public.catalogo_normalizar_texto(p_texto text)
returns text language sql immutable returns null on null input
set search_path = public, pg_temp
as $$
  select trim(regexp_replace(regexp_replace(
    translate(lower(p_texto),'áàãâäéèêëíìîïóòõôöúùûüç','aaaaaeeeeiiiiooooouuuuc'),
    '[^[:alnum:] -]+',' ','g'),'[[:space:]]+',' ','g'));
$$;

create or replace function public.registrar_busca_catalogo(
  p_termo text,
  p_programa text default null,
  p_resultados integer default 0,
  p_dedupe_token text default null
)
returns boolean language plpgsql security definer
set search_path = public, pg_temp
as $$
declare
  v_termo text := trim(coalesce(p_termo, ''));
  v_programa text := nullif(trim(coalesce(p_programa, '')), '');
  v_normalizado text;
  v_rows integer := 0;
begin
  if char_length(v_termo) < 2 or char_length(v_termo) > 120 then return false; end if;
  if upper(v_termo) ~ '^[0-9]{4}[A-Z][0-9]{5,6}$' then return false; end if;
  if v_programa is not null and char_length(v_programa) > 120 then return false; end if;
  if p_dedupe_token is null or char_length(p_dedupe_token) < 16 or char_length(p_dedupe_token) > 128 then return false; end if;

  v_normalizado := public.catalogo_normalizar_texto(v_termo);
  if char_length(coalesce(v_normalizado, '')) < 2 then return false; end if;

  insert into public.catalogo_search_events (termo, termo_normalizado, programa, resultados, dedupe_token)
  values (v_termo, v_normalizado, v_programa, greatest(0, least(coalesce(p_resultados, 0), 1000000)), p_dedupe_token)
  on conflict (dedupe_token) do nothing;

  get diagnostics v_rows = row_count;
  return v_rows = 1;
end;
$$;

create or replace function public.catalogo_populares_geral(p_dias integer default 30,p_limite integer default 6)
returns table (termo text, quantidade bigint)
language sql stable security definer set search_path = public, pg_temp
as $$
  with base as (
    select termo_normalizado,(array_agg(termo order by created_at desc))[1] as termo_exibicao,count(*)::bigint as quantidade
    from public.catalogo_search_events
    where created_at >= now() - make_interval(days => greatest(1, least(coalesce(p_dias, 30), 365)))
    group by termo_normalizado
  )
  select termo_exibicao::text, quantidade from base
  order by quantidade desc, termo_exibicao asc
  limit greatest(1, least(coalesce(p_limite, 6), 20));
$$;

create or replace function public.catalogo_populares_programa(p_programa text,p_dias integer default 30,p_limite integer default 5)
returns table (termo text, quantidade bigint)
language sql stable security definer set search_path = public, pg_temp
as $$
  with base as (
    select termo_normalizado,(array_agg(termo order by created_at desc))[1] as termo_exibicao,count(*)::bigint as quantidade
    from public.catalogo_search_events
    where created_at >= now() - make_interval(days => greatest(1, least(coalesce(p_dias, 30), 365)))
      and programa is not null
      and public.catalogo_normalizar_texto(programa) = public.catalogo_normalizar_texto(p_programa)
    group by termo_normalizado
  )
  select termo_exibicao::text, quantidade from base
  order by quantidade desc, termo_exibicao asc
  limit greatest(1, least(coalesce(p_limite, 5), 20));
$$;

create or replace function public.catalogo_buscas_sem_resultado(p_dias integer default 30,p_limite integer default 20)
returns table (termo text, programa text, quantidade bigint, ultima_busca timestamptz)
language sql stable security definer set search_path = public, pg_temp
as $$
  with base as (
    select termo_normalizado,coalesce(programa, '') as programa_chave,
      (array_agg(termo order by created_at desc))[1] as termo_exibicao,
      (array_agg(programa order by created_at desc))[1] as programa_exibicao,
      count(*)::bigint as quantidade,max(created_at) as ultima_busca
    from public.catalogo_search_events
    where resultados = 0
      and created_at >= now() - make_interval(days => greatest(1, least(coalesce(p_dias, 30), 365)))
    group by termo_normalizado, coalesce(programa, '')
  )
  select termo_exibicao::text, programa_exibicao::text, quantidade, ultima_busca from base
  order by quantidade desc, ultima_busca desc
  limit greatest(1, least(coalesce(p_limite, 20), 100));
$$;

create or replace function public.catalogo_programas_mais_consultados(p_dias integer default 30,p_limite integer default 20)
returns table (programa text, quantidade bigint)
language sql stable security definer set search_path = public, pg_temp
as $$
  with base as (
    select public.catalogo_normalizar_texto(programa) as programa_normalizado,
      (array_agg(programa order by created_at desc))[1] as programa_exibicao,
      count(*)::bigint as quantidade
    from public.catalogo_search_events
    where programa is not null and trim(programa) <> ''
      and created_at >= now() - make_interval(days => greatest(1, least(coalesce(p_dias, 30), 365)))
    group by public.catalogo_normalizar_texto(programa)
  )
  select programa_exibicao::text, quantidade from base
  order by quantidade desc, programa_exibicao asc
  limit greatest(1, least(coalesce(p_limite, 20), 100));
$$;

-- Fecha privilegios implicitos de PUBLIC e das roles padrao.
revoke all on function public.catalogo_normalizar_texto(text) from public, anon, authenticated;
revoke all on function public.registrar_busca_catalogo(text, text, integer, text) from public, anon, authenticated;
revoke all on function public.catalogo_populares_geral(integer, integer) from public, anon, authenticated;
revoke all on function public.catalogo_populares_programa(text, integer, integer) from public, anon, authenticated;
revoke all on function public.catalogo_buscas_sem_resultado(integer, integer) from public, anon, authenticated;
revoke all on function public.catalogo_programas_mais_consultados(integer, integer) from public, anon, authenticated;

-- API publica minima do catalogo.
grant execute on function public.registrar_busca_catalogo(text, text, integer, text) to anon, authenticated;
grant execute on function public.catalogo_populares_geral(integer, integer) to anon, authenticated;
grant execute on function public.catalogo_populares_programa(text, integer, integer) to anon, authenticated;

-- Relatorios editoriais sensiveis: somente backend/service role.
grant execute on function public.catalogo_buscas_sem_resultado(integer, integer) to service_role;
grant execute on function public.catalogo_programas_mais_consultados(integer, integer) to service_role;
